In [1]:
import numpy as np
import pandas as pd
from imageio import imread
import matplotlib.pyplot as plt
from matplotlib import cm
import seaborn as sns
import os
from common import *
from models import own_LinRegGD
import cv2
import tensorflow as tf

print(f"Root directory: {os.getcwd()}")
plt.rcParams.update({
    "text.usetex": True,
    "font.family": "serif",
    "font.serif": ["Palatino"],
    "font.size": 10,
})

#%matplotlib

Root directory: c:\Users\andre\Dropbox\FYS-STK4155_projects\FYS-STK4155 - Project2\FYS-STK4155-Prj2_report\code


In [2]:
def relu(x):
    return np.maximum(0,x)

In [3]:
class Layer:
    def __init__(self, nbf_inputs : int, nbf_outputs : int, activation_function=lambda x: x):
        self.input = nbf_inputs
        self.output = nbf_outputs
        self.activation = activation_function
        self.weights = np.random.rand(nbf_inputs, nbf_outputs) # TODO: include possible negative weight initialization
        self.bias = np.random.rand(1, nbf_outputs) # TODO: include possible negative weight initialization
        self.accumulated_gradient = np.zeros_like(self.weights)

    def forward_prop(self, input : np.ndarray) -> np.ndarray:
        z = (input @ self.weights) + self.bias
        a = self.activation(z)
        return a, self.weights, self.bias

    def backward_prop(self, X, y):
        h = self.forward_prop(X)
        error = y - y_hat 

        # TODO: DO backprop




In [6]:
np.random.seed(4155)
X = np.array([[-1, 0],
              [1, 0 ]])
hidden1 = Layer(nbf_inputs=2, nbf_outputs=2)#, activation_function=relu)

y_hat, w, b = hidden1.forward_prop(X)
print(w,"\n")
print(b,"\n")
print(y_hat)


[[0.81341245 0.91175391]
 [0.81501125 0.90847179]] 

[[0.58902609 0.99301661]] 

[[-0.22438636  0.08126271]
 [ 1.40243854  1.90477052]]
