In [1]:
import numpy as np
import pandas as pd
from imageio import imread
import matplotlib.pyplot as plt
from matplotlib import cm
import seaborn as sns
import os
from common import *
from models import own_LinRegGD
import cv2
#import tensorflow as tf
from models import NeuralNetwork, Layer, Fixed_layer, binary_classifier, relu

print(f"Root directory: {os.getcwd()}")
plt.rcParams.update({
    "text.usetex": True,
    "font.family": "serif",
    "font.serif": ["Palatino"],
    "font.size": 10,
})

#%matplotlib

Root directory: /home/arefrode/uio/fys-stk4155/projects/FYS-STK4155-Prj2_report/code


# XOR classification
The following code checks that a Fixed neural net is able to correctly classify the XOR problem

In [2]:
np.random.seed(4155)
X = np.array([[1, 0],
              [0, 1],
              [1, 1],
              [0, 0]])

hidden1 = Fixed_layer(nbf_inputs=2, nbf_outputs=2, weights=np.array([[1,1],[1,1]]), bias=np.array([-1.5, -0.5]), activation_function=binary_classifier)
output = Fixed_layer(nbf_inputs=2, nbf_outputs=1, weights=np.array([-1,1]), bias=np.array([-0.5]), activation_function=binary_classifier)

model = NeuralNetwork()
model.add_layer(hidden1)
model.add_layer(output)

y_hat = model.predict(X)
print(f"y_hat: {y_hat}")

[[1 0]
 [0 1]
 [1 1]
 [0 0]] 

[[1 1]
 [1 1]] 

[-1.5 -0.5] 

[[0 1]
 [0 1]
 [1 1]
 [0 0]] 

[-1  1] 

[-0.5] 

y_hat: [1 1 0 0]


In [3]:
np.random.seed(4155)
X = np.array([[-1, 0],
              [1, 0 ]])
hidden1 = Layer(nbf_inputs=2, nbf_outputs=1, activation_function=relu)

model2 = NeuralNetwork()
model2.add_layer(hidden1)
y_hat = model2.predict(X)
print(y_hat)

[[-1  0]
 [ 1  0]] 

[[0.31341245]
 [0.41175391]] 

[[0.31501125]] 

[[0.0015988]
 [0.6284237]]
